name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
shu       uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Instalar dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requerimientos.txt ]; then pip install -r requerimientos.txt; fi
    - name: Revisión de Estilo de código
      run: |
        pylint ArbolesRojinegros.py
    - name: Tests
      run: |
        pytest
